//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBD_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrenamiento
    {
        public Entrenamiento()
        {
            this.EntrenamientoHerramienta = new HashSet<EntrenamientoHerramienta>();
            this.EntrenamientoMaquina = new HashSet<EntrenamientoMaquina>();
            this.EntrenamientoTipoEntrenamiento = new HashSet<EntrenamientoTipoEntrenamiento>();
            this.JugadorEntrenamiento = new HashSet<JugadorEntrenamiento>();
        }
    
        public int idEntrenamiento { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<bool> estatus { get; set; }
        public Nullable<int> idUsuarioCrea { get; set; }
        public Nullable<System.DateTime> fechaCrea { get; set; }
        public Nullable<int> idUsuarioModifica { get; set; }
        public Nullable<System.DateTime> fechaModifica { get; set; }
    
        public virtual ICollection<EntrenamientoHerramienta> EntrenamientoHerramienta { get; set; }
        public virtual ICollection<EntrenamientoMaquina> EntrenamientoMaquina { get; set; }
        public virtual ICollection<EntrenamientoTipoEntrenamiento> EntrenamientoTipoEntrenamiento { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual ICollection<JugadorEntrenamiento> JugadorEntrenamiento { get; set; }
    }
}
