//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBD_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        public Equipo()
        {
            this.Empleado = new HashSet<Empleado>();
            this.EquipoFichaje = new HashSet<EquipoFichaje>();
            this.EquipoPrestamoJugador = new HashSet<EquipoPrestamoJugador>();
            this.EquipoTrofeo = new HashSet<EquipoTrofeo>();
            this.EstadisticaTemporada = new HashSet<EstadisticaTemporada>();
            this.Jersey = new HashSet<Jersey>();
            this.Jugador = new HashSet<Jugador>();
            this.Partido = new HashSet<Partido>();
            this.Partido1 = new HashSet<Partido>();
            this.Presidente = new HashSet<Presidente>();
            this.Viaje = new HashSet<Viaje>();
        }
    
        public int idEquipo { get; set; }
        public string nombre { get; set; }
        public int idLiga { get; set; }
        public Nullable<bool> estatus { get; set; }
        public Nullable<int> idUsuarioCrea { get; set; }
        public Nullable<System.DateTime> fechaCrea { get; set; }
        public Nullable<int> idUsuarioModifica { get; set; }
        public Nullable<System.DateTime> fechaModifica { get; set; }
    
        public virtual ICollection<Empleado> Empleado { get; set; }
        public virtual ICollection<EquipoFichaje> EquipoFichaje { get; set; }
        public virtual Liga Liga { get; set; }
        public virtual ICollection<EquipoPrestamoJugador> EquipoPrestamoJugador { get; set; }
        public virtual ICollection<EquipoTrofeo> EquipoTrofeo { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual ICollection<EstadisticaTemporada> EstadisticaTemporada { get; set; }
        public virtual ICollection<Jersey> Jersey { get; set; }
        public virtual ICollection<Jugador> Jugador { get; set; }
        public virtual ICollection<Partido> Partido { get; set; }
        public virtual ICollection<Partido> Partido1 { get; set; }
        public virtual ICollection<Presidente> Presidente { get; set; }
        public virtual ICollection<Viaje> Viaje { get; set; }
    }
}
