//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBD_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadisticaTemporada
    {
        public EstadisticaTemporada()
        {
            this.TemporadaEstadisticaTemporada = new HashSet<TemporadaEstadisticaTemporada>();
        }
    
        public int idEstadisticaTemporada { get; set; }
        public int partidosGanados { get; set; }
        public int partidosPerdidos { get; set; }
        public int partidosEmpatados { get; set; }
        public int idEquipo { get; set; }
        public Nullable<bool> estatus { get; set; }
        public Nullable<int> idUsuarioCrea { get; set; }
        public Nullable<System.DateTime> fechaCrea { get; set; }
        public Nullable<int> idUsuarioModifica { get; set; }
        public Nullable<System.DateTime> fechaModifica { get; set; }
    
        public virtual Equipo Equipo { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual ICollection<TemporadaEstadisticaTemporada> TemporadaEstadisticaTemporada { get; set; }
    }
}
