//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBD_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estadio
    {
        public Estadio()
        {
            this.Boleto = new HashSet<Boleto>();
            this.EmpleadoEstadio = new HashSet<EmpleadoEstadio>();
            this.Palco = new HashSet<Palco>();
            this.Partido = new HashSet<Partido>();
            this.Venta = new HashSet<Venta>();
        }
    
        public int idEstadio { get; set; }
        public string nombre { get; set; }
        public int capacidad { get; set; }
        public string calle { get; set; }
        public string numExterior { get; set; }
        public string cp { get; set; }
        public int idAsentamiento { get; set; }
        public int idCiudad { get; set; }
        public Nullable<bool> estatus { get; set; }
        public Nullable<int> idUsuarioCrea { get; set; }
        public Nullable<System.DateTime> fechaCrea { get; set; }
        public Nullable<int> idUsuarioModifica { get; set; }
        public Nullable<System.DateTime> fechaModifica { get; set; }
    
        public virtual Asentamiento Asentamiento { get; set; }
        public virtual ICollection<Boleto> Boleto { get; set; }
        public virtual Ciudad Ciudad { get; set; }
        public virtual ICollection<EmpleadoEstadio> EmpleadoEstadio { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual ICollection<Palco> Palco { get; set; }
        public virtual ICollection<Partido> Partido { get; set; }
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
