//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBD_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugador
    {
        public Jugador()
        {
            this.Fichaje = new HashSet<Fichaje>();
            this.JugadorEntrenamiento = new HashSet<JugadorEntrenamiento>();
            this.JugadorPartido = new HashSet<JugadorPartido>();
            this.JugadorPremio = new HashSet<JugadorPremio>();
            this.PosicionJugador = new HashSet<PosicionJugador>();
            this.PrestamoJugador = new HashSet<PrestamoJugador>();
        }
    
        public int idJugador { get; set; }
        public string nombre { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public int idNacionalidad { get; set; }
        public int idManager { get; set; }
        public int idContrato { get; set; }
        public int idDorsal { get; set; }
        public int idEquipo { get; set; }
        public Nullable<bool> estatus { get; set; }
        public Nullable<int> idUsuarioCrea { get; set; }
        public Nullable<System.DateTime> fechaCrea { get; set; }
        public Nullable<int> idUsuarioModifica { get; set; }
        public Nullable<System.DateTime> fechaModifica { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        public virtual Dorsal Dorsal { get; set; }
        public virtual Equipo Equipo { get; set; }
        public virtual ICollection<Fichaje> Fichaje { get; set; }
        public virtual ICollection<JugadorEntrenamiento> JugadorEntrenamiento { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Nacionalidad Nacionalidad { get; set; }
        public virtual ICollection<JugadorPartido> JugadorPartido { get; set; }
        public virtual ICollection<JugadorPremio> JugadorPremio { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual ICollection<PosicionJugador> PosicionJugador { get; set; }
        public virtual ICollection<PrestamoJugador> PrestamoJugador { get; set; }
    }
}
