//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBD_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liga
    {
        public Liga()
        {
            this.Equipo = new HashSet<Equipo>();
            this.Temporada = new HashSet<Temporada>();
        }
    
        public int idLiga { get; set; }
        public string numero { get; set; }
        public string nombre { get; set; }
        public int idPais { get; set; }
        public Nullable<bool> estatus { get; set; }
        public Nullable<int> idUsuarioCrea { get; set; }
        public Nullable<System.DateTime> fechaCrea { get; set; }
        public Nullable<int> idUsuarioModifica { get; set; }
        public Nullable<System.DateTime> fechaModifica { get; set; }
    
        public virtual ICollection<Equipo> Equipo { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual ICollection<Temporada> Temporada { get; set; }
    }
}
