//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBD_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partido
    {
        public Partido()
        {
            this.ArbitroPartido = new HashSet<ArbitroPartido>();
            this.JugadorPartido = new HashSet<JugadorPartido>();
            this.PartidoPatrocinador = new HashSet<PartidoPatrocinador>();
            this.PartidoTipoPartido = new HashSet<PartidoTipoPartido>();
        }
    
        public int idPartido { get; set; }
        public System.DateTime fecha { get; set; }
        public int idEquipoLocal { get; set; }
        public int idEquipoVisitante { get; set; }
        public int idEstadio { get; set; }
        public int idEstadistica { get; set; }
        public Nullable<bool> estatus { get; set; }
        public Nullable<int> idUsuarioCrea { get; set; }
        public Nullable<System.DateTime> fechaCrea { get; set; }
        public Nullable<int> idUsuarioModifica { get; set; }
        public Nullable<System.DateTime> fechaModifica { get; set; }
    
        public virtual ICollection<ArbitroPartido> ArbitroPartido { get; set; }
        public virtual Equipo Equipo { get; set; }
        public virtual Equipo Equipo1 { get; set; }
        public virtual Estadio Estadio { get; set; }
        public virtual Estadistica Estadistica { get; set; }
        public virtual ICollection<JugadorPartido> JugadorPartido { get; set; }
        public virtual ICollection<PartidoPatrocinador> PartidoPatrocinador { get; set; }
        public virtual ICollection<PartidoTipoPartido> PartidoTipoPartido { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
