//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBD_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoFutbolEntities1 : DbContext
    {
        public ProyectoFutbolEntities1()
            : base("name=ProyectoFutbolEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Arbitro> Arbitro { get; set; }
        public DbSet<ArbitroPartido> ArbitroPartido { get; set; }
        public DbSet<ArbitroTipoArbitro> ArbitroTipoArbitro { get; set; }
        public DbSet<Articulo> Articulo { get; set; }
        public DbSet<Asentamiento> Asentamiento { get; set; }
        public DbSet<AsentamientoTipoAsentamiento> AsentamientoTipoAsentamiento { get; set; }
        public DbSet<Boleto> Boleto { get; set; }
        public DbSet<Campo> Campo { get; set; }
        public DbSet<Ciudad> Ciudad { get; set; }
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<ClienteMembresia> ClienteMembresia { get; set; }
        public DbSet<Contrato> Contrato { get; set; }
        public DbSet<Dorsal> Dorsal { get; set; }
        public DbSet<Empleado> Empleado { get; set; }
        public DbSet<EmpleadoEstadio> EmpleadoEstadio { get; set; }
        public DbSet<EmpleadoTipoEmpleado> EmpleadoTipoEmpleado { get; set; }
        public DbSet<Entrenamiento> Entrenamiento { get; set; }
        public DbSet<EntrenamientoHerramienta> EntrenamientoHerramienta { get; set; }
        public DbSet<EntrenamientoMaquina> EntrenamientoMaquina { get; set; }
        public DbSet<EntrenamientoTipoEntrenamiento> EntrenamientoTipoEntrenamiento { get; set; }
        public DbSet<Equipo> Equipo { get; set; }
        public DbSet<EquipoFichaje> EquipoFichaje { get; set; }
        public DbSet<EquipoPrestamoJugador> EquipoPrestamoJugador { get; set; }
        public DbSet<EquipoTrofeo> EquipoTrofeo { get; set; }
        public DbSet<Estadio> Estadio { get; set; }
        public DbSet<Estadistica> Estadistica { get; set; }
        public DbSet<EstadisticaTemporada> EstadisticaTemporada { get; set; }
        public DbSet<Estado> Estado { get; set; }
        public DbSet<Fichaje> Fichaje { get; set; }
        public DbSet<Gimnasio> Gimnasio { get; set; }
        public DbSet<Herramienta> Herramienta { get; set; }
        public DbSet<HerramientaCampo> HerramientaCampo { get; set; }
        public DbSet<Hotel> Hotel { get; set; }
        public DbSet<HotelSucursal> HotelSucursal { get; set; }
        public DbSet<Jersey> Jersey { get; set; }
        public DbSet<Jugador> Jugador { get; set; }
        public DbSet<JugadorEntrenamiento> JugadorEntrenamiento { get; set; }
        public DbSet<JugadorPartido> JugadorPartido { get; set; }
        public DbSet<JugadorPremio> JugadorPremio { get; set; }
        public DbSet<Liga> Liga { get; set; }
        public DbSet<Manager> Manager { get; set; }
        public DbSet<Maquina> Maquina { get; set; }
        public DbSet<MaquinaGimnasio> MaquinaGimnasio { get; set; }
        public DbSet<Marca> Marca { get; set; }
        public DbSet<MarcaJersey> MarcaJersey { get; set; }
        public DbSet<MedioTransporte> MedioTransporte { get; set; }
        public DbSet<Membresia> Membresia { get; set; }
        public DbSet<Nacionalidad> Nacionalidad { get; set; }
        public DbSet<Pais> Pais { get; set; }
        public DbSet<Palco> Palco { get; set; }
        public DbSet<Partido> Partido { get; set; }
        public DbSet<PartidoPatrocinador> PartidoPatrocinador { get; set; }
        public DbSet<PartidoTipoPartido> PartidoTipoPartido { get; set; }
        public DbSet<Patrocinador> Patrocinador { get; set; }
        public DbSet<Posicion> Posicion { get; set; }
        public DbSet<PosicionJugador> PosicionJugador { get; set; }
        public DbSet<Premio> Premio { get; set; }
        public DbSet<PremioTipoPremio> PremioTipoPremio { get; set; }
        public DbSet<Presidente> Presidente { get; set; }
        public DbSet<PrestamoJugador> PrestamoJugador { get; set; }
        public DbSet<Sucursal> Sucursal { get; set; }
        public DbSet<Temporada> Temporada { get; set; }
        public DbSet<TemporadaEstadisticaTemporada> TemporadaEstadisticaTemporada { get; set; }
        public DbSet<TipoArbitro> TipoArbitro { get; set; }
        public DbSet<TipoAsentamiento> TipoAsentamiento { get; set; }
        public DbSet<TipoEmpleado> TipoEmpleado { get; set; }
        public DbSet<TipoEntrenamiento> TipoEntrenamiento { get; set; }
        public DbSet<TipoPartido> TipoPartido { get; set; }
        public DbSet<TipoPremio> TipoPremio { get; set; }
        public DbSet<Trofeo> Trofeo { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Venta> Venta { get; set; }
        public DbSet<VentaArticulo> VentaArticulo { get; set; }
        public DbSet<Viaje> Viaje { get; set; }
        public DbSet<ViajeMedioTransporte> ViajeMedioTransporte { get; set; }
        public DbSet<Zona> Zona { get; set; }
    }
}
