//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBD_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Arbitro = new HashSet<Arbitro>();
            this.Arbitro1 = new HashSet<Arbitro>();
            this.ArbitroPartido = new HashSet<ArbitroPartido>();
            this.ArbitroPartido1 = new HashSet<ArbitroPartido>();
            this.ArbitroTipoArbitro = new HashSet<ArbitroTipoArbitro>();
            this.ArbitroTipoArbitro1 = new HashSet<ArbitroTipoArbitro>();
            this.Articulo = new HashSet<Articulo>();
            this.Articulo1 = new HashSet<Articulo>();
            this.Asentamiento = new HashSet<Asentamiento>();
            this.Asentamiento1 = new HashSet<Asentamiento>();
            this.AsentamientoTipoAsentamiento = new HashSet<AsentamientoTipoAsentamiento>();
            this.AsentamientoTipoAsentamiento1 = new HashSet<AsentamientoTipoAsentamiento>();
            this.Boleto = new HashSet<Boleto>();
            this.Boleto1 = new HashSet<Boleto>();
            this.Campo = new HashSet<Campo>();
            this.Campo1 = new HashSet<Campo>();
            this.Ciudad = new HashSet<Ciudad>();
            this.Ciudad1 = new HashSet<Ciudad>();
            this.Cliente = new HashSet<Cliente>();
            this.Cliente1 = new HashSet<Cliente>();
            this.ClienteMembresia = new HashSet<ClienteMembresia>();
            this.ClienteMembresia1 = new HashSet<ClienteMembresia>();
            this.Contrato = new HashSet<Contrato>();
            this.Contrato1 = new HashSet<Contrato>();
            this.Dorsal = new HashSet<Dorsal>();
            this.Dorsal1 = new HashSet<Dorsal>();
            this.Empleado = new HashSet<Empleado>();
            this.Empleado1 = new HashSet<Empleado>();
            this.EmpleadoEstadio = new HashSet<EmpleadoEstadio>();
            this.EmpleadoEstadio1 = new HashSet<EmpleadoEstadio>();
            this.EmpleadoTipoEmpleado = new HashSet<EmpleadoTipoEmpleado>();
            this.EmpleadoTipoEmpleado1 = new HashSet<EmpleadoTipoEmpleado>();
            this.Entrenamiento = new HashSet<Entrenamiento>();
            this.Entrenamiento1 = new HashSet<Entrenamiento>();
            this.EntrenamientoHerramienta = new HashSet<EntrenamientoHerramienta>();
            this.EntrenamientoHerramienta1 = new HashSet<EntrenamientoHerramienta>();
            this.EntrenamientoMaquina = new HashSet<EntrenamientoMaquina>();
            this.EntrenamientoMaquina1 = new HashSet<EntrenamientoMaquina>();
            this.EntrenamientoTipoEntrenamiento = new HashSet<EntrenamientoTipoEntrenamiento>();
            this.EntrenamientoTipoEntrenamiento1 = new HashSet<EntrenamientoTipoEntrenamiento>();
            this.Equipo = new HashSet<Equipo>();
            this.Equipo1 = new HashSet<Equipo>();
            this.EquipoFichaje = new HashSet<EquipoFichaje>();
            this.EquipoFichaje1 = new HashSet<EquipoFichaje>();
            this.EquipoPrestamoJugador = new HashSet<EquipoPrestamoJugador>();
            this.EquipoPrestamoJugador1 = new HashSet<EquipoPrestamoJugador>();
            this.EquipoTrofeo = new HashSet<EquipoTrofeo>();
            this.EquipoTrofeo1 = new HashSet<EquipoTrofeo>();
            this.Estadio = new HashSet<Estadio>();
            this.Estadio1 = new HashSet<Estadio>();
            this.Estadistica = new HashSet<Estadistica>();
            this.Estadistica1 = new HashSet<Estadistica>();
            this.EstadisticaTemporada = new HashSet<EstadisticaTemporada>();
            this.EstadisticaTemporada1 = new HashSet<EstadisticaTemporada>();
            this.Estado = new HashSet<Estado>();
            this.Estado1 = new HashSet<Estado>();
            this.Fichaje = new HashSet<Fichaje>();
            this.Fichaje1 = new HashSet<Fichaje>();
            this.Gimnasio = new HashSet<Gimnasio>();
            this.Gimnasio1 = new HashSet<Gimnasio>();
            this.Herramienta = new HashSet<Herramienta>();
            this.Herramienta1 = new HashSet<Herramienta>();
            this.HerramientaCampo = new HashSet<HerramientaCampo>();
            this.HerramientaCampo1 = new HashSet<HerramientaCampo>();
            this.Hotel = new HashSet<Hotel>();
            this.Hotel1 = new HashSet<Hotel>();
            this.HotelSucursal = new HashSet<HotelSucursal>();
            this.HotelSucursal1 = new HashSet<HotelSucursal>();
            this.Jersey = new HashSet<Jersey>();
            this.Jersey1 = new HashSet<Jersey>();
            this.Jugador = new HashSet<Jugador>();
            this.Jugador1 = new HashSet<Jugador>();
            this.JugadorEntrenamiento = new HashSet<JugadorEntrenamiento>();
            this.JugadorEntrenamiento1 = new HashSet<JugadorEntrenamiento>();
            this.JugadorPartido = new HashSet<JugadorPartido>();
            this.JugadorPartido1 = new HashSet<JugadorPartido>();
            this.JugadorPremio = new HashSet<JugadorPremio>();
            this.JugadorPremio1 = new HashSet<JugadorPremio>();
            this.Liga = new HashSet<Liga>();
            this.Liga1 = new HashSet<Liga>();
            this.Manager = new HashSet<Manager>();
            this.Manager1 = new HashSet<Manager>();
            this.Maquina = new HashSet<Maquina>();
            this.Maquina1 = new HashSet<Maquina>();
            this.MaquinaGimnasio = new HashSet<MaquinaGimnasio>();
            this.MaquinaGimnasio1 = new HashSet<MaquinaGimnasio>();
            this.Marca = new HashSet<Marca>();
            this.Marca1 = new HashSet<Marca>();
            this.MarcaJersey = new HashSet<MarcaJersey>();
            this.MarcaJersey1 = new HashSet<MarcaJersey>();
            this.MedioTransporte = new HashSet<MedioTransporte>();
            this.MedioTransporte1 = new HashSet<MedioTransporte>();
            this.Membresia = new HashSet<Membresia>();
            this.Membresia1 = new HashSet<Membresia>();
            this.Nacionalidad = new HashSet<Nacionalidad>();
            this.Nacionalidad1 = new HashSet<Nacionalidad>();
            this.Pais = new HashSet<Pais>();
            this.Pais1 = new HashSet<Pais>();
            this.Palco = new HashSet<Palco>();
            this.Palco1 = new HashSet<Palco>();
            this.Partido = new HashSet<Partido>();
            this.Partido1 = new HashSet<Partido>();
            this.PartidoPatrocinador = new HashSet<PartidoPatrocinador>();
            this.PartidoPatrocinador1 = new HashSet<PartidoPatrocinador>();
            this.PartidoTipoPartido = new HashSet<PartidoTipoPartido>();
            this.PartidoTipoPartido1 = new HashSet<PartidoTipoPartido>();
            this.Patrocinador = new HashSet<Patrocinador>();
            this.Patrocinador1 = new HashSet<Patrocinador>();
            this.Posicion = new HashSet<Posicion>();
            this.Posicion1 = new HashSet<Posicion>();
            this.PosicionJugador = new HashSet<PosicionJugador>();
            this.PosicionJugador1 = new HashSet<PosicionJugador>();
            this.Premio = new HashSet<Premio>();
            this.Premio1 = new HashSet<Premio>();
            this.PremioTipoPremio = new HashSet<PremioTipoPremio>();
            this.PremioTipoPremio1 = new HashSet<PremioTipoPremio>();
            this.Presidente = new HashSet<Presidente>();
            this.Presidente1 = new HashSet<Presidente>();
            this.PrestamoJugador = new HashSet<PrestamoJugador>();
            this.PrestamoJugador1 = new HashSet<PrestamoJugador>();
            this.Sucursal = new HashSet<Sucursal>();
            this.Sucursal1 = new HashSet<Sucursal>();
            this.Temporada = new HashSet<Temporada>();
            this.Temporada1 = new HashSet<Temporada>();
            this.TemporadaEstadisticaTemporada = new HashSet<TemporadaEstadisticaTemporada>();
            this.TemporadaEstadisticaTemporada1 = new HashSet<TemporadaEstadisticaTemporada>();
            this.TipoArbitro = new HashSet<TipoArbitro>();
            this.TipoArbitro1 = new HashSet<TipoArbitro>();
            this.TipoAsentamiento = new HashSet<TipoAsentamiento>();
            this.TipoAsentamiento1 = new HashSet<TipoAsentamiento>();
            this.TipoEmpleado = new HashSet<TipoEmpleado>();
            this.TipoEmpleado1 = new HashSet<TipoEmpleado>();
            this.TipoEntrenamiento = new HashSet<TipoEntrenamiento>();
            this.TipoEntrenamiento1 = new HashSet<TipoEntrenamiento>();
            this.TipoPartido = new HashSet<TipoPartido>();
            this.TipoPartido1 = new HashSet<TipoPartido>();
            this.TipoPremio = new HashSet<TipoPremio>();
            this.TipoPremio1 = new HashSet<TipoPremio>();
            this.Trofeo = new HashSet<Trofeo>();
            this.Trofeo1 = new HashSet<Trofeo>();
            this.VentaArticulo = new HashSet<VentaArticulo>();
            this.VentaArticulo1 = new HashSet<VentaArticulo>();
            this.Venta = new HashSet<Venta>();
            this.Venta1 = new HashSet<Venta>();
            this.ViajeMedioTransporte = new HashSet<ViajeMedioTransporte>();
            this.ViajeMedioTransporte1 = new HashSet<ViajeMedioTransporte>();
            this.Viaje = new HashSet<Viaje>();
            this.Viaje1 = new HashSet<Viaje>();
            this.Zona = new HashSet<Zona>();
            this.Zona1 = new HashSet<Zona>();
        }
    
        public int idUsuario { get; set; }
        public string nombre { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public string correo { get; set; }
        public string clave { get; set; }
        public Nullable<bool> estatus { get; set; }
        public Nullable<int> idUsuarioCrea { get; set; }
        public Nullable<System.DateTime> fechaCrea { get; set; }
        public Nullable<int> idUsuarioModifica { get; set; }
        public Nullable<System.DateTime> fechaModifica { get; set; }
    
        public virtual ICollection<Arbitro> Arbitro { get; set; }
        public virtual ICollection<Arbitro> Arbitro1 { get; set; }
        public virtual ICollection<ArbitroPartido> ArbitroPartido { get; set; }
        public virtual ICollection<ArbitroPartido> ArbitroPartido1 { get; set; }
        public virtual ICollection<ArbitroTipoArbitro> ArbitroTipoArbitro { get; set; }
        public virtual ICollection<ArbitroTipoArbitro> ArbitroTipoArbitro1 { get; set; }
        public virtual ICollection<Articulo> Articulo { get; set; }
        public virtual ICollection<Articulo> Articulo1 { get; set; }
        public virtual ICollection<Asentamiento> Asentamiento { get; set; }
        public virtual ICollection<Asentamiento> Asentamiento1 { get; set; }
        public virtual ICollection<AsentamientoTipoAsentamiento> AsentamientoTipoAsentamiento { get; set; }
        public virtual ICollection<AsentamientoTipoAsentamiento> AsentamientoTipoAsentamiento1 { get; set; }
        public virtual ICollection<Boleto> Boleto { get; set; }
        public virtual ICollection<Boleto> Boleto1 { get; set; }
        public virtual ICollection<Campo> Campo { get; set; }
        public virtual ICollection<Campo> Campo1 { get; set; }
        public virtual ICollection<Ciudad> Ciudad { get; set; }
        public virtual ICollection<Ciudad> Ciudad1 { get; set; }
        public virtual ICollection<Cliente> Cliente { get; set; }
        public virtual ICollection<Cliente> Cliente1 { get; set; }
        public virtual ICollection<ClienteMembresia> ClienteMembresia { get; set; }
        public virtual ICollection<ClienteMembresia> ClienteMembresia1 { get; set; }
        public virtual ICollection<Contrato> Contrato { get; set; }
        public virtual ICollection<Contrato> Contrato1 { get; set; }
        public virtual ICollection<Dorsal> Dorsal { get; set; }
        public virtual ICollection<Dorsal> Dorsal1 { get; set; }
        public virtual ICollection<Empleado> Empleado { get; set; }
        public virtual ICollection<Empleado> Empleado1 { get; set; }
        public virtual ICollection<EmpleadoEstadio> EmpleadoEstadio { get; set; }
        public virtual ICollection<EmpleadoEstadio> EmpleadoEstadio1 { get; set; }
        public virtual ICollection<EmpleadoTipoEmpleado> EmpleadoTipoEmpleado { get; set; }
        public virtual ICollection<EmpleadoTipoEmpleado> EmpleadoTipoEmpleado1 { get; set; }
        public virtual ICollection<Entrenamiento> Entrenamiento { get; set; }
        public virtual ICollection<Entrenamiento> Entrenamiento1 { get; set; }
        public virtual ICollection<EntrenamientoHerramienta> EntrenamientoHerramienta { get; set; }
        public virtual ICollection<EntrenamientoHerramienta> EntrenamientoHerramienta1 { get; set; }
        public virtual ICollection<EntrenamientoMaquina> EntrenamientoMaquina { get; set; }
        public virtual ICollection<EntrenamientoMaquina> EntrenamientoMaquina1 { get; set; }
        public virtual ICollection<EntrenamientoTipoEntrenamiento> EntrenamientoTipoEntrenamiento { get; set; }
        public virtual ICollection<EntrenamientoTipoEntrenamiento> EntrenamientoTipoEntrenamiento1 { get; set; }
        public virtual ICollection<Equipo> Equipo { get; set; }
        public virtual ICollection<Equipo> Equipo1 { get; set; }
        public virtual ICollection<EquipoFichaje> EquipoFichaje { get; set; }
        public virtual ICollection<EquipoFichaje> EquipoFichaje1 { get; set; }
        public virtual ICollection<EquipoPrestamoJugador> EquipoPrestamoJugador { get; set; }
        public virtual ICollection<EquipoPrestamoJugador> EquipoPrestamoJugador1 { get; set; }
        public virtual ICollection<EquipoTrofeo> EquipoTrofeo { get; set; }
        public virtual ICollection<EquipoTrofeo> EquipoTrofeo1 { get; set; }
        public virtual ICollection<Estadio> Estadio { get; set; }
        public virtual ICollection<Estadio> Estadio1 { get; set; }
        public virtual ICollection<Estadistica> Estadistica { get; set; }
        public virtual ICollection<Estadistica> Estadistica1 { get; set; }
        public virtual ICollection<EstadisticaTemporada> EstadisticaTemporada { get; set; }
        public virtual ICollection<EstadisticaTemporada> EstadisticaTemporada1 { get; set; }
        public virtual ICollection<Estado> Estado { get; set; }
        public virtual ICollection<Estado> Estado1 { get; set; }
        public virtual ICollection<Fichaje> Fichaje { get; set; }
        public virtual ICollection<Fichaje> Fichaje1 { get; set; }
        public virtual ICollection<Gimnasio> Gimnasio { get; set; }
        public virtual ICollection<Gimnasio> Gimnasio1 { get; set; }
        public virtual ICollection<Herramienta> Herramienta { get; set; }
        public virtual ICollection<Herramienta> Herramienta1 { get; set; }
        public virtual ICollection<HerramientaCampo> HerramientaCampo { get; set; }
        public virtual ICollection<HerramientaCampo> HerramientaCampo1 { get; set; }
        public virtual ICollection<Hotel> Hotel { get; set; }
        public virtual ICollection<Hotel> Hotel1 { get; set; }
        public virtual ICollection<HotelSucursal> HotelSucursal { get; set; }
        public virtual ICollection<HotelSucursal> HotelSucursal1 { get; set; }
        public virtual ICollection<Jersey> Jersey { get; set; }
        public virtual ICollection<Jersey> Jersey1 { get; set; }
        public virtual ICollection<Jugador> Jugador { get; set; }
        public virtual ICollection<Jugador> Jugador1 { get; set; }
        public virtual ICollection<JugadorEntrenamiento> JugadorEntrenamiento { get; set; }
        public virtual ICollection<JugadorEntrenamiento> JugadorEntrenamiento1 { get; set; }
        public virtual ICollection<JugadorPartido> JugadorPartido { get; set; }
        public virtual ICollection<JugadorPartido> JugadorPartido1 { get; set; }
        public virtual ICollection<JugadorPremio> JugadorPremio { get; set; }
        public virtual ICollection<JugadorPremio> JugadorPremio1 { get; set; }
        public virtual ICollection<Liga> Liga { get; set; }
        public virtual ICollection<Liga> Liga1 { get; set; }
        public virtual ICollection<Manager> Manager { get; set; }
        public virtual ICollection<Manager> Manager1 { get; set; }
        public virtual ICollection<Maquina> Maquina { get; set; }
        public virtual ICollection<Maquina> Maquina1 { get; set; }
        public virtual ICollection<MaquinaGimnasio> MaquinaGimnasio { get; set; }
        public virtual ICollection<MaquinaGimnasio> MaquinaGimnasio1 { get; set; }
        public virtual ICollection<Marca> Marca { get; set; }
        public virtual ICollection<Marca> Marca1 { get; set; }
        public virtual ICollection<MarcaJersey> MarcaJersey { get; set; }
        public virtual ICollection<MarcaJersey> MarcaJersey1 { get; set; }
        public virtual ICollection<MedioTransporte> MedioTransporte { get; set; }
        public virtual ICollection<MedioTransporte> MedioTransporte1 { get; set; }
        public virtual ICollection<Membresia> Membresia { get; set; }
        public virtual ICollection<Membresia> Membresia1 { get; set; }
        public virtual ICollection<Nacionalidad> Nacionalidad { get; set; }
        public virtual ICollection<Nacionalidad> Nacionalidad1 { get; set; }
        public virtual ICollection<Pais> Pais { get; set; }
        public virtual ICollection<Pais> Pais1 { get; set; }
        public virtual ICollection<Palco> Palco { get; set; }
        public virtual ICollection<Palco> Palco1 { get; set; }
        public virtual ICollection<Partido> Partido { get; set; }
        public virtual ICollection<Partido> Partido1 { get; set; }
        public virtual ICollection<PartidoPatrocinador> PartidoPatrocinador { get; set; }
        public virtual ICollection<PartidoPatrocinador> PartidoPatrocinador1 { get; set; }
        public virtual ICollection<PartidoTipoPartido> PartidoTipoPartido { get; set; }
        public virtual ICollection<PartidoTipoPartido> PartidoTipoPartido1 { get; set; }
        public virtual ICollection<Patrocinador> Patrocinador { get; set; }
        public virtual ICollection<Patrocinador> Patrocinador1 { get; set; }
        public virtual ICollection<Posicion> Posicion { get; set; }
        public virtual ICollection<Posicion> Posicion1 { get; set; }
        public virtual ICollection<PosicionJugador> PosicionJugador { get; set; }
        public virtual ICollection<PosicionJugador> PosicionJugador1 { get; set; }
        public virtual ICollection<Premio> Premio { get; set; }
        public virtual ICollection<Premio> Premio1 { get; set; }
        public virtual ICollection<PremioTipoPremio> PremioTipoPremio { get; set; }
        public virtual ICollection<PremioTipoPremio> PremioTipoPremio1 { get; set; }
        public virtual ICollection<Presidente> Presidente { get; set; }
        public virtual ICollection<Presidente> Presidente1 { get; set; }
        public virtual ICollection<PrestamoJugador> PrestamoJugador { get; set; }
        public virtual ICollection<PrestamoJugador> PrestamoJugador1 { get; set; }
        public virtual ICollection<Sucursal> Sucursal { get; set; }
        public virtual ICollection<Sucursal> Sucursal1 { get; set; }
        public virtual ICollection<Temporada> Temporada { get; set; }
        public virtual ICollection<Temporada> Temporada1 { get; set; }
        public virtual ICollection<TemporadaEstadisticaTemporada> TemporadaEstadisticaTemporada { get; set; }
        public virtual ICollection<TemporadaEstadisticaTemporada> TemporadaEstadisticaTemporada1 { get; set; }
        public virtual ICollection<TipoArbitro> TipoArbitro { get; set; }
        public virtual ICollection<TipoArbitro> TipoArbitro1 { get; set; }
        public virtual ICollection<TipoAsentamiento> TipoAsentamiento { get; set; }
        public virtual ICollection<TipoAsentamiento> TipoAsentamiento1 { get; set; }
        public virtual ICollection<TipoEmpleado> TipoEmpleado { get; set; }
        public virtual ICollection<TipoEmpleado> TipoEmpleado1 { get; set; }
        public virtual ICollection<TipoEntrenamiento> TipoEntrenamiento { get; set; }
        public virtual ICollection<TipoEntrenamiento> TipoEntrenamiento1 { get; set; }
        public virtual ICollection<TipoPartido> TipoPartido { get; set; }
        public virtual ICollection<TipoPartido> TipoPartido1 { get; set; }
        public virtual ICollection<TipoPremio> TipoPremio { get; set; }
        public virtual ICollection<TipoPremio> TipoPremio1 { get; set; }
        public virtual ICollection<Trofeo> Trofeo { get; set; }
        public virtual ICollection<Trofeo> Trofeo1 { get; set; }
        public virtual ICollection<VentaArticulo> VentaArticulo { get; set; }
        public virtual ICollection<VentaArticulo> VentaArticulo1 { get; set; }
        public virtual ICollection<Venta> Venta { get; set; }
        public virtual ICollection<Venta> Venta1 { get; set; }
        public virtual ICollection<ViajeMedioTransporte> ViajeMedioTransporte { get; set; }
        public virtual ICollection<ViajeMedioTransporte> ViajeMedioTransporte1 { get; set; }
        public virtual ICollection<Viaje> Viaje { get; set; }
        public virtual ICollection<Viaje> Viaje1 { get; set; }
        public virtual ICollection<Zona> Zona { get; set; }
        public virtual ICollection<Zona> Zona1 { get; set; }
    }
}
